Repository rtCamp/snapwp, pull requests merged in 2025-03, with the labels that each got.

#103 refactor!: Change `location` to `groupLocation` for script placement enum type
  .changeset/fluffy-crabs-rhyme.md
  packages/core/src/props/index.ts
  packages/next/README.md
  packages/next/src/components/script.tsx
  packages/next/src/template-renderer/template-scripts.tsx
  packages/query/src/queries/get-current-template.graphql
Labels: breaking change🚨, status: hold ⏸️

#127 ci: prettier format on changesets pr
  .github/workflows/release_packages.yml
Labels: needs: review 🧐

#111 feat: robust handling for internal uri
  .changeset/eleven-experts-feel.md
  .changeset/salty-moments-yell.md
  .env.example
  .github/workflows/pull_request_examples.yml
  docs/config-api.md
  docs/cors.md
  docs/getting-started.md
  examples/nextjs/starter/.env.example
  examples/nextjs/starter/codegen.ts
  packages/blocks/jest.setup.js
  packages/blocks/src/blocks/core-button.tsx
  packages/blocks/src/blocks/tests/__snapshots__/core-button.test.tsx.snap
  packages/blocks/src/blocks/tests/core-button.test.tsx
  packages/cli/README.md
  packages/core/README.md
  packages/core/jest.setup.js
  packages/core/src/config/snapwp-config-manager.ts
  packages/core/src/config/tests/snapwp-config-manager.test.tsx
  packages/core/src/utils/generate-graphql-url.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/is-valid-url.ts
  packages/core/src/utils/replace-host-url.ts
  packages/core/src/utils/styles/cn.ts
  packages/core/src/utils/styles/find-element-and-get-class-names.ts
  packages/core/src/utils/styles/get-class-names-from-string.ts
  packages/core/src/utils/styles/get-color-class-name.ts
  packages/core/src/utils/styles/get-image-size-from-attributes.ts
  packages/core/src/utils/styles/get-px-for-size-attribute.ts
  packages/core/src/utils/styles/get-spacing-preset-css-var.ts
  packages/core/src/utils/styles/get-style-object-from-string.ts
  packages/core/src/utils/styles/get-styles-from-attributes.ts
  packages/core/src/utils/styles/tests/cn.test.ts
  packages/core/src/utils/styles/tests/find-element-and-get-class-names.test.ts
  packages/core/src/utils/styles/tests/get-class-names-from-string.test.ts
  packages/core/src/utils/styles/tests/get-color-class-name.test.ts
  packages/core/src/utils/styles/tests/get-image-size-from-attributes.test.ts
  packages/core/src/utils/styles/tests/get-px-for-size-attribute.test.ts
  packages/core/src/utils/styles/tests/get-spacing-preset-css-var.test.ts
  packages/core/src/utils/styles/tests/get-style-object-from-string.test.ts
  packages/core/src/utils/styles/tests/get-styles-from-attributes.test.ts
  packages/core/src/utils/tests/generate-graphql-url.test.ts
  packages/core/src/utils/tests/is-valid-url.test.ts
  packages/core/src/utils/tests/replace-host-url.test.ts
  packages/core/src/utils/url/tests/transformers.test.ts
  packages/core/src/utils/url/tests/validators.test.ts
  packages/core/src/utils/url/transformers.ts
  packages/core/src/utils/url/validators.ts
  packages/next/src/components/image.tsx
  packages/next/src/components/link.tsx
  packages/next/src/config/with-snap-wp.ts
  packages/next/src/middleware/cors.ts
  packages/next/src/middleware/proxies.ts
  packages/next/src/middleware/utils.ts
  packages/next/src/template-renderer/template-scripts.tsx
  packages/query/codegen.ts
  packages/query/src/query-engine/index.ts
  packages/types/src/global/env.ts
Labels: status: hold ⏸️
